/**
 * 从 index.html 生成简历 Markdown（中英双份）。
 *
 * 设计意图：简历内容与站点同源。文案改在 index.html 里，重跑本脚本即同步，
 * 避免「页面改了、简历忘了改」的漂移。站点运行时仍是单文件、无构建依赖。
 *
 * 用法：
 *   cd C:/Users/20534/.workbuddy/binaries/node/workspace
 *   NODE_PATH=".../node_modules" node "C:/andy/codebase/my-profile/tools/build-resume.cjs"
 */
const fs = require("node:fs");
const path = require("node:path");
const { JSDOM, VirtualConsole } = require("jsdom");

const ROOT = "C:/andy/codebase/my-profile";
const ENTRY = path.join(ROOT, "index.html");
const html = fs.readFileSync(ENTRY, "utf8");

const vc = new VirtualConsole();
vc.on("jsdomError", (e) => {
  if (!/Not implemented/.test(e.message)) console.error("[jsdom] " + e.message);
});

const dom = new JSDOM(html, {
  runScripts: "dangerously",
  pretendToBeVisual: true,
  url: "http://localhost/index.html",
  virtualConsole: vc,
});
const { window } = dom;
const doc = window.document;
window.Element.prototype.scrollIntoView = function () {};
window.scrollTo = function () {};

const txt = (el) => (el ? el.textContent.replace(/\s+/g, " ").trim() : "");
const all = (sel) => Array.from(doc.querySelectorAll(sel));

const CONTACT = {
  zh: {
    email: "andy.dev@example.com",
    github: "github.com/andyxu1234",
    wechat: "andy-ai-dev",
    file: "resume.md",
    download: "Andy-AI应用开发工程师-简历.md",
    title: "# Andy · AI 应用开发工程师",
    role: "AI 应用开发工程师",
    genNote: "<!-- 本文件由 tools/build-resume.cjs 从 index.html 自动生成，请勿手改；改文案请改 index.html 后重跑脚本 -->",
    labels: {
      intent: "求职意向", about: "关于我", exp: "经历", skills: "技能", works: "项目经历",
      highlights: "核心工作与亮点", stack: "技术栈", generated: "本文件由个人主页内容自动生成",
      site: "个人主页", stats: "数据一览", period: "时间", role_: "角色",
    },
  },
  en: {
    email: "andy.dev@example.com",
    github: "github.com/andyxu1234",
    wechat: "andy-ai-dev",
    file: "resume-en.md",
    download: "Andy-AI-Application-Engineer-Resume.md",
    title: "# Andy · AI Application Engineer",
    role: "AI Application Engineer",
    genNote: "<!-- Auto-generated by tools/build-resume.cjs from index.html. Do not edit by hand. -->",
    labels: {
      intent: "Target role & preferences", about: "About", exp: "Experience", skills: "Skills", works: "Selected projects",
      highlights: "Highlights", stack: "Tech stack", generated: "Generated from the personal site content",
      site: "Portfolio", stats: "At a glance", period: "Period", role_: "Role",
    },
  },
};

const WORKS = window.eval("WORKS");
const L = (lang, k) => window.eval("I18N")[lang][k] ?? "";

function snapshot(lang) {
  window.setLang(lang);
  const pick = (o) => (o && typeof o === "object" ? o[lang] ?? o.zh ?? o.en : o);
  return {
    // hero
    eyebrow: L(lang, "hero_eyebrow"),
    loc: L(lang, "hero_loc"),
    lead: txt(doc.querySelector(".hero p.lead")),
    // 求职意向（首屏 facts 列表）
    intent: all(".hero-facts div").map((d) => [txt(d.querySelector("dt")), txt(d.querySelector("dd"))]),
    // 关于
    aboutParas: all(".about-grid p").map(txt).filter(Boolean),
    stats: all(".stat").map((s) => `${txt(s.querySelector("b"))} ${txt(s.querySelector("span"))}`),
    // 经历
    exp: all(".timeline li").map((li) => ({
      period: txt(li.querySelector(".tl-period")),
      role: txt(li.querySelector(".tl-role")),
      org: txt(li.querySelector(".tl-org")),
      desc: txt(li.querySelector(".tl-desc")),
    })),
    // 技能
    skills: all(".skill-card").map((c) => ({
      title: txt(c.querySelector("h3")),
      sub: txt(c.querySelector(".skill-sub")),
      pills: all(".skill-card").length ? Array.from(c.querySelectorAll(".pill")).map(txt) : [],
    })),
    // 项目（取数据源，字段比卡片更全）
    works: WORKS.map((w) => ({
      title: pick(w.title), tag: pick(w.tag), period: pick(w.period), role: pick(w.role),
      summary: pick(w.summary), desc: pick(w.desc), highlights: pick(w.highlights), stack: w.stack,
      tryUrl: w.tryUrl, codeUrl: w.codeUrl,
    })),
  };
}

function build(lang) {
  const c = CONTACT[lang];
  const lb = c.labels;
  const s = snapshot(lang);
  const out = [];

  out.push(c.genNote, "");
  out.push(c.title, "");
  out.push(`> ${s.loc}`);
  out.push(`> ✉ ${c.email} ｜ GitHub ${c.github} ｜ ${lang === "zh" ? "微信" : "WeChat"} ${c.wechat}`, "");

  out.push(`## ${lb.intent}`, "");
  for (const [k, v] of s.intent) out.push(`- **${k}**：${v}`);
  out.push("");

  out.push(`## ${lb.about}`, "");
  for (const p of s.aboutParas) out.push(p, "");
  if (s.stats.length) out.push(`**${lb.stats}**：${s.stats.slice(0, 3).join(" · ")}`, "");

  out.push(`## ${lb.exp}`, "");
  for (const e of s.exp) {
    out.push(`### ${e.role}${e.org ? ` ｜ ${e.org}` : ""}`);
    out.push(`\`${e.period}\``);
    if (e.desc) out.push("", e.desc);
    out.push("");
  }

  out.push(`## ${lb.skills}`, "");
  for (const k of s.skills) {
    out.push(`- **${k.title}**：${k.pills.join(" · ")}`);
  }
  out.push("");

  out.push(`## ${lb.works}`, "");
  s.works.forEach((w, i) => {
    out.push(`### ${i + 1}. ${w.title}`);
    out.push(`\`${w.period}\` ｜ ${w.role} ｜ ${w.tag}`);
    const links = [];
    if (w.codeUrl) links.push(`[${lang === "zh" ? "源码" : "Source"}](${w.codeUrl})`);
    // 只收录绝对链接：相对路径的站内 demo 在简历单独外发时会失效
    if (w.tryUrl && /^https?:/i.test(w.tryUrl)) links.push(`[${lang === "zh" ? "在线体验" : "Live demo"}](${w.tryUrl})`);
    if (links.length) out.push(links.join(" ｜ "));
    out.push("", w.summary, "");
    if (w.desc) out.push(w.desc, "");
    out.push(`**${lb.highlights}**`, "");
    for (const h of w.highlights) out.push(`- ${h}`);
    out.push("", `**${lb.stack}**：${w.stack.join(" · ")}`, "");
  });

  out.push("---", "");
  out.push(`_${lb.generated}（${lb.site}：index.html）_`);

  return { markdown: out.join("\n").replace(/\n{3,}/g, "\n\n"), file: c.file, download: c.download };
}

const written = [];
for (const lang of ["zh", "en"]) {
  const { markdown, file } = build(lang);
  const p = path.join(ROOT, file);
  fs.writeFileSync(p, markdown, "utf8");
  written.push({ file, bytes: Buffer.byteLength(markdown, "utf8") });
}

console.log("已生成：");
for (const w of written) console.log(`  ${w.file}  (${(w.bytes / 1024).toFixed(1)} KB)`);
console.log("\n下载按钮映射：");
console.log(`  zh -> resume.md  (download: ${CONTACT.zh.download})`);
console.log(`  en -> resume-en.md  (download: ${CONTACT.en.download})`);
